import { McpServer as UpstreamMCPServer } from "@modelcontextprotocol/sdk/server/mcp.js";

import * as get_fred_category from "./get_fred_category.js";
import * as get_fred_category_children from "./get_fred_category_children.js";
import * as get_fred_category_related from "./get_fred_category_related.js";
import * as get_fred_category_series from "./get_fred_category_series.js";
import * as get_fred_category_tags from "./get_fred_category_tags.js";
import * as get_fred_category_related_tags from "./get_fred_category_related_tags.js";
import * as get_fred_releases from "./get_fred_releases.js";
import * as get_fred_releases_dates from "./get_fred_releases_dates.js";
import * as get_fred_release from "./get_fred_release.js";
import * as get_fred_release_dates from "./get_fred_release_dates.js";
import * as get_fred_release_series from "./get_fred_release_series.js";
import * as get_fred_release_sources from "./get_fred_release_sources.js";
import * as get_fred_release_tags from "./get_fred_release_tags.js";
import * as get_fred_release_related_tags from "./get_fred_release_related_tags.js";
import * as get_fred_release_tables from "./get_fred_release_tables.js";
import * as get_fred_series from "./get_fred_series.js";
import * as get_fred_series_categories from "./get_fred_series_categories.js";
import * as get_fred_series_observations from "./get_fred_series_observations.js";
import * as get_fred_series_release from "./get_fred_series_release.js";
import * as get_fred_series_search from "./get_fred_series_search.js";
import * as get_fred_series_search_tags from "./get_fred_series_search_tags.js";
import * as get_fred_series_search_related_tags from "./get_fred_series_search_related_tags.js";
import * as get_fred_series_tags from "./get_fred_series_tags.js";
import * as get_fred_series_updates from "./get_fred_series_updates.js";
import * as get_fred_series_vintagedates from "./get_fred_series_vintagedates.js";
import * as get_fred_sources from "./get_fred_sources.js";
import * as get_fred_source from "./get_fred_source.js";
import * as get_fred_source_releases from "./get_fred_source_releases.js";
import * as get_fred_tags from "./get_fred_tags.js";
import * as get_fred_related_tags from "./get_fred_related_tags.js";
import * as get_fred_tags_series from "./get_fred_tags_series.js";

export function setupAllTools<S extends UpstreamMCPServer>(server: S) {
  get_fred_category.setupTool(server);
  get_fred_category_children.setupTool(server);
  get_fred_category_related.setupTool(server);
  get_fred_category_series.setupTool(server);
  get_fred_category_tags.setupTool(server);
  get_fred_category_related_tags.setupTool(server);
  get_fred_releases.setupTool(server);
  get_fred_releases_dates.setupTool(server);
  get_fred_release.setupTool(server);
  get_fred_release_dates.setupTool(server);
  get_fred_release_series.setupTool(server);
  get_fred_release_sources.setupTool(server);
  get_fred_release_tags.setupTool(server);
  get_fred_release_related_tags.setupTool(server);
  get_fred_release_tables.setupTool(server);
  get_fred_series.setupTool(server);
  get_fred_series_categories.setupTool(server);
  get_fred_series_observations.setupTool(server);
  get_fred_series_release.setupTool(server);
  get_fred_series_search.setupTool(server);
  get_fred_series_search_tags.setupTool(server);
  get_fred_series_search_related_tags.setupTool(server);
  get_fred_series_tags.setupTool(server);
  get_fred_series_updates.setupTool(server);
  get_fred_series_vintagedates.setupTool(server);
  get_fred_sources.setupTool(server);
  get_fred_source.setupTool(server);
  get_fred_source_releases.setupTool(server);
  get_fred_tags.setupTool(server);
  get_fred_related_tags.setupTool(server);
  get_fred_tags_series.setupTool(server);
}
